language: go
dist: trusty
addons:
  apt:
    packages:
    - realpath
go:
- "1.9"
- "1.10"
- "1.11"

git:
  depth: 3

install:
- go get -u ./...
- go get -u github.com/onsi/ginkgo/ginkgo github.com/onsi/gomega github.com/mattn/goveralls
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.3

script:
- ginkgo -p -r -race -randomizeAllSpecs -randomizeSuites -failOnPending -trace -compilers 2
- golangci-lint run ./...

after_success:
- ginkgo -r -covermode=set
- 'echo "mode: atomic" > profile'
- tail -q -n+2 $(find -name "*\.coverprofile") >> profile
- goveralls -coverprofile=profile -service=travis-ci -repotoken $COVERALLS_TOKEN
