language: go
dist: trusty
addons:
  apt:
    packages:
    - realpath
go:
- "1.10"
- "1.11"

git:
  depth: 3

install:
- go get -u github.com/mattn/goveralls
- make depend

script:
- make lint
- make test

after_success:
- ginkgo -r -covermode=set
- 'echo "mode: atomic" > profile'
- tail -q -n+2 $(find -name "*\.coverprofile") >> profile
- goveralls -coverprofile=profile -service=travis-ci -repotoken $COVERALLS_TOKEN
